language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.6
  
env:
  - DB=mysql
  - DB=mysqli
  - DB=pdo/mysql

sudo: false

before_script:
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm
      env: DB=pgsql
    - php: hhvm
      env: DB=pdo/pgsql
    - php: 7.0
      env: DB=mysql
    - php: 7.1
      env: DB=mysql